
# base image
FROM node:14

# set working directory
WORKDIR /

# add `/app/node_modules/.bin` to $PATH
ENV PATH /node_modules/.bin:$PATH

# install and cache app dependencies
RUN npm install

# start app
CMD ["npm", "start"]